name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
      - name: Install MAUI Workload
        run: dotnet workload install maui --ignore-failed-sources
      - name: Test
        run: |
          dotnet test Wrecept.Core.Tests/Wrecept.Core.Tests.csproj --no-build --collect:"XPlat Code Coverage"
          dotnet test tests/Wrecept.Tests/Wrecept.Tests.csproj --no-build --collect:"XPlat Code Coverage"
          dotnet test tests/Wrecept.Storage.Tests/Wrecept.Storage.Tests.csproj --no-build --collect:"XPlat Code Coverage"
