name: CI

on:
  push:
  pull_request:

jobs:
  core-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Run core tests
        run: dotnet test Wrecept.Core.sln --filter "Category!=UI"

  ui-tests:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Start WinAppDriver
        run: Start-Process -FilePath "C:\\Program Files (x86)\\Windows Application Driver\\WinAppDriver.exe" -ArgumentList "127.0.0.1 4723" -PassThru
      - name: Build app
        run: dotnet publish Wrecept.UI/Wrecept.UI.csproj -c Release -o build
      - name: Run UI tests
        run: dotnet test tests/Wrecept.UI.AutomatedTests/Wrecept.UI.AutomatedTests.csproj --no-build
